### ISSUE TITLE
harga ambil dari penerimaan apa ngisi sendiri?

### ISSUE THREAD

**Issue by Aryaaazrr** [Aryaaazrr/pnbp_itik_2024#1]
![Screenshot 2024-10-30 104203](https://github.com/user-attachments/assets/7b427932-9ceb-48ad-a947-098235b518f6)

**Comment by Aryaaazrr** [comment]
pp

**Comment by Aryaaazrr** [comment]
buruan aku siang ada task

**Comment by Aryaaazrr** [comment]
woo lama

**Comment by NillaPutriRosidania** [comment]
ngisi sendiri
